<?php
function xml_journal_article_theme($existing, $type, $theme, $path) {
    return array(
        'xml_display_doaj' => array(
            'variables' => array(
                'node_es' => NULL,
                'node_en' => NULL
            ),
            'template' => 'xml-display-doaj',
        ),
        'xml_display_pubmed' => array(
            'variables' => array(
                'node_es' => NULL,
                'node_en' => NULL
            ),
            'template' => 'xml-display-pubmed',
        ),
        'xml_error' => array(
            'template' => 'xml-error',
        ),
    );
}